### ISSUE TITLE
Unable to run Android

### ISSUE THREAD

**Issue by weitzhandler** [unoplatform/Uno.Xaml-Controls-Gallery#56]
**Describe the bug**
When trying to run the Android head, I get an exception saying "Root frame not found".

**Steps to reproduce the bug**
Just trying to debug the app on Android Emulator.
An exception is thrown saying "Root frame not found":

**Expected behavior**
App should be able to launch on Android.

**Actual behavior**
App crashes during launch.

**Screenshots**
![image](https://user-images.githubusercontent.com/2716316/71651506-c6784780-2d26-11ea-8522-b0051873c01f.png)

**Version Info**
Gallery version (found on Settings page): 
1.1.1.0

Device form factor:
- [ ] Desktop
- [x] Mobile - Android
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Comment by navio-n** [comment]
I had the same error on my device. App.xaml.cs in Shared project:

//rootFrame = (Frame)rootPage.FindName("rootFrame"); //Android 10.0 returns null
rootFrame = NavigationRootPage.RootFrame; //Android 10.0 workaround
