### ISSUE TITLE
[WASM] Colors do not change when switching between Light and Dark Theme

### ISSUE THREAD

**Issue by StewartPolsky** [unoplatform/Uno.Xaml-Controls-Gallery#66]
**Describe the bug**

Colors do not change when switching between Light and Dark Theme

**Steps to reproduce the bug**

1. Go to https://xamlcontrolsgallery.platform.uno/
2. Click on Settings in the bottom left corner
3. Select Light / Dark Theme
4. Notice that color theme does not change

**Expected behavior**

When Selecting Light / Dark theme the color should change

**Actual behavior**

When Selecting Light / Dark theme the color does not change

**Screenshots**

![xaml gallery dark mode toggle](https://user-images.githubusercontent.com/49959074/82827633-6a50c400-9e7d-11ea-8055-eeff136f80aa.png)

**Version Info**

Gallery version (found on Settings page): 

0.1.0-uno.1+246

Windows 10 version:
- [ ] Insider Build (xxxxx)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)
- [x] 1909 Build 18363.836 

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Additional context**

**Comment by jeromelaban** [comment]
Fixed in recent builds of uno
